# Generated by Django 5.2.8 on 2025-11-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField()),
                ('instructor_name', models.CharField()),
                ('start_date', models.IntegerField()),
                ('end_date', models.IntegerField()),
                ('course_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_id', models.CharField()),
                ('name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.IntegerField()),
                ('courses_taught', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_id', models.CharField()),
                ('semester_name', models.CharField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status_status', models.CharField(choices=[('Enrolled', 'Enrolled'), ('Unenrolled', 'Unenrolled')], default='Enrolled')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('password', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('birthdate', models.DateField()),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestingDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tuition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('payment_date', models.DateField()),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Paid')),
            ],
        ),
    ]
